### ISSUE TITLE
compilation failed (alr with gnoga) uxstring1.ads/adb error

### ISSUE THREAD

**Issue by JulienGioux** [Blady-Com/gnoga#1]
Hi.
I experience trouble when trying tu test gnoga with alire.
I've create a new test project with alr and add gnoga as dependency :
```
alr init --bin test
cd test
alr with gnoga
```
For this test i have modified src/test.adb based on the simple "hello world" from the doc.
but `alr build` complain about uxstrings1
```
uxstrings1.ads:96:81: error: strings are delimited by double quote character
uxstrings1.ads:108:92: error: strings are delimited by double quote character
uxstrings1.ads:111:73: error: strings are delimited by double quote character
uxstrings1.adb:122:90: warning: formal parameter "Item" is not referenced [-gnatwf]
uxstrings1.adb:124:36: warning: UXString_Read unimplemented [enabled by default]
uxstrings1.adb:316:13: error: not fully conformant with declaration at uxstrings1.ads:92
uxstrings1.adb:316:13: error: default expression for "Substitute" does not match
gnoga-gui-base.adb:123:07: warning: named number "No_Button" is not referenced [-gnatwu]

   compilation of uxstrings1.adb failed
   compilation of test.adb failed
```

**Comment by Blady-Com** [comment]
Hi Julien,
There is a mismatch with compilation options of withed crate.
As a workaround, you have to add -gnatW8 compiler option in your main GPR project file.
Keep me informed, thanks Pascal.

**Comment by JulienGioux** [comment]
> 
That's it, server is running :)
Sorry for my stupid questions, i am a kind of newbie with Ada ^^

I think it would be nice to adapt the doc for Alire users, cause it was needed to find and copie folders from .test/alire/cache/dependencies/gnoga_2.1.2_5f127c56/templates/gnoga_make/hello_world/ to my root project and I was unable to use gnoga_make...

Simple suggestion but what do you think about splitting the alire project with one to use as library, one for the tools, one for demo, one for tutos etc... ?

**Comment by Blady-Com** [comment]
Alire support is still on going, for a while...
Thanks for your suggestion but I need some help to do so.
Do you know how to do it with Alire?
