### ISSUE TITLE
Keyboard event record needs a new field added, "key" and probably some constants for it.

### ISSUE THREAD

**Issue by jere-software** [Blady-Com/gnoga#8]
https://github.com/Blady-Com/gnoga/blob/ad8052f33ade03e8edf1078013240595dfc757bf/src/gnoga-gui-base.ads#L368

This record currently provides Key_Char and Key_Code fields for determining which key was press.  Key_Code is platform dependent and can vary, so it isn't good for cross platform.  Key_Char is only provided by the Key_Press event, but that event is deprecated and on some browsers doesn't return correctly for all keys.  

Additionally both Key_Char and Key_Code are deprecated fields (also including "keypress" event here):
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/charCode
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode
https://developer.mozilla.org/en-US/docs/Web/API/Element/keypress_event

Now the standard wants everyone to use the "key" property:
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key

Which returns a semi-formatted string (for printable characters, it is just the printed value, for others it is a predefined string or other value as noted in that link).  

I want to propose we add the Key property to this record.  It would either need to be some type of unbounded string or a uxstring since the length can vary.  I don't know if since this is an event if efficiency of UxString vs an ubounded string type (Wide_Wide??) is better to consider for the field.

For backwards compatibility we should probably leave the Key_Char and Key_Code in for older browsers at least until the standard completely removes them.

**Comment by Blady-Com** [comment]
Thanks for your proposal!
I agree it would valuable to get it in Gnoga.
I'm going to froze the version 2.2.
It would be ok for next coming version 2.3.
As it may contain unicode characters, UXStrings are suitable.
Just say String as it has been redefined to UXString in gnoga.ads.
Do you mind to propose an implementation in a pull request?

**Comment by jere-software** [comment]
@Blady-Com I can try.  I don't 100% fully understand the javascript side, but I can maybe try to gen something up.  Sorry for the late reply.  I didn't get a notification there was an update here.

EDIT:  If I do figure it out, what branch do I pull request against?  I didn't see a 2.3 branch

**Comment by jere-software** [comment]
@Blady-Com I issued a pull request against Master in lieu of a 2.3 branch

https://github.com/Blady-Com/gnoga/pull/9
